# Generated by Django 2.2.7 on 2019-12-02 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants_count',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='occupants_count',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
